default:
  image: node:20
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - node_modules

stages:
  - install
  - test
  - build
  - deploy

.before_script: &pnpm_before_script
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
    - SHELL="$(which bash)" pnpm setup
    - source ~/.bashrc

install:
  stage: install
  script:
    - pnpm install --frozen-lockfile
  <<: *pnpm_before_script

test:
  stage: test
  script:
    - pnpm run test
  <<: *pnpm_before_script

format:
  stage: test
  script:
    - pnpm run format:check
  <<: *pnpm_before_script

lint:
  stage: test
  script:
    - pnpm run lint
  <<: *pnpm_before_script

test:helm:
  stage: test
  image: ghcr.io/vojtechmares/toolkit:latest
  script:
    - helm lint ./charts/website
    - helm template website ./charts/website

build:docker:
  stage: build
  image: docker:git
  variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker info
  script:
    - docker buildx create --name website --use
    - docker buildx build --provenance=false --platform linux/amd64,linux/arm64 -t $IMAGE:$TAG --push .
    - docker manifest inspect $IMAGE:$TAG
  # no cache is needed here
  # this makes job faster, since it does not have to pull the cache
  cache: []

deploy:staging:
  stage: deploy
  image: ghcr.io/vojtechmares/toolkit:latest
  variables:
    # shallow clone
    GIT_DEPTH: 1
    IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script: >
    helm upgrade --install --namespace website-staging \
      website ./charts/website \
      --values ./charts/website/values.staging.yaml \
      --set image.tag=$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  environment:
    name: staging
    url: https://staging.website.vmdevel.cz

deploy:production:
  stage: deploy
  image: ghcr.io/vojtechmares/toolkit:latest
  variables:
    # shallow clone
    GIT_DEPTH: 1
    IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script: >
    helm upgrade --install --namespace website-production \
      website ./charts/website \
      --values ./charts/website/values.production.yaml \
      --set image.tag=$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == 'production'
  environment:
    name: production
    url: https://wwww.mares.cz
