# https://taskfile.dev

version: "3"

dotenv:
  - .prod.env

vars:
  IMAGE_NAME: mares-cz
  CONTAINER_NAME: mares-cz

tasks:
  build:
    desc: Build the Docker image
    cmds:
      - docker build -t {{.IMAGE_NAME}} .

  run:
    desc: Run the web app in a Docker container
    deps: [build]
    cmds:
      - docker run --rm
        --name {{.CONTAINER_NAME}}
        -p 8080:8080
        -e HOST=0.0.0.0
        -e PORT=8080
        --env-file .prod.env
        {{.IMAGE_NAME}}

  stop:
    desc: Stop the running container
    cmds:
      - docker stop {{.CONTAINER_NAME}}
