# hostname: www.example.com

# redirects:
#   enabled: true

#   permanent: true
#   hosts:
#     - example.com

image:
  repository: ghcr.io/vojtechmares/mares.cz/web
  tag: latest

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 1Gi

config:
  host: beta.mares.cz

  port: 8080

  env:
    SESSIONS_API_URL: https://api.example.com

secrets:
  oidcCredentials: some-secret-store-key

replicas: 2
