redirects:
  enabled: true
  permanent: true

  hosts:
    - staging.website.maresdev.com

config:
  host: beta.mares.cz
  env:
    SESSIONS_API_URL: https://api.mares-skoleni.cz

secrets:
  oidcCredentials: website-mares-cz-oidc-credentials
