image:
  pullSecrets:
    - name: mareshq-gitlab-registry

replicas: 2

ingress:
  host: staging.website.vmdevel.cz
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

config:
  apiKey: "3b1effbcbab4c76c2601ab908294700e5af22ca08082459d64a06cc080ac7641"

cron:
  refreshBlog:
    enabled: true
