image:
  pullSecrets:
    - name: mareshq-gitlab-registry

replicas: 2

ingress:
  host: www.mares.cz
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-production
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

config:
  suppressGoogleAnalytics: false
  apiKey: "0abc3573b122b2d4fcc0ea6ad91bc426d860b842f0fcb9ada83dfa5bec83042f"

cron:
  refreshBlog:
    enabled: true
