services:
  app:
    container_name: mares-cz-web
    # using env variable $TAG to specify the image tag
    image: registry.mareshq.com/hq/website:${TAG}
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      HOSTNAME: "0.0.0.0"
      SUPPRESS_GOOGLE_ANALYTICS: "false"
      PORT: 3000
      CMS_API_URL: https://cms.mareshq.com/api
      CMS_API_TOKEN: ${CMS_API_TOKEN}
      API_KEY: 0abc3573b122b2d4fcc0ea6ad91bc426d860b842f0fcb9ada83dfa5bec83042f
    volumes:
      - /srv/mares-cz-website/cache:/app/.next/cache
    networks:
      - mares-cz-net

networks:
  mares-cz-net:
    name: mares-cz-net
    driver: bridge
