apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "8080"
  SESSIONS_API_URL: {{ .Values.config.env.SESSIONS_API_URL | quote }}
