---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-fetch-strapi-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    name: {{ .Release.Name }}-strapi-credentials
  data:
    - secretKey: STRAPI_API_TOKEN
      remoteRef:
        key: website-mares-cz-strapi-credentials/STRAPI_API_TOKEN
