---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-fetch-notion-credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    name: {{ .Release.Name }}-notion-credentials
  data:
    - secretKey: NOTION_API_KEY
      remoteRef:
        key: website-mares-cz-notion-credentials/NOTION_API_KEY
    - secretKey: NOTION_TRAINING_SESSIONS_DATABASE_ID
      remoteRef:
        key: website-mares-cz-notion-credentials/NOTION_TRAINING_SESSIONS_DATABASE_ID
