---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-fetch-oidc-credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    name: {{ .Release.Name }}-oidc-credentials
  data:
    - secretKey: SESSIONS_OIDC_ISSUER
      remoteRef:
        key: {{ .Values.secrets.oidcCredentials }}/SESSIONS_OIDC_ISSUER
    - secretKey: SESSIONS_OIDC_CLIENT_ID
      remoteRef:
        key: {{ .Values.secrets.oidcCredentials }}/SESSIONS_OIDC_CLIENT_ID
    - secretKey: SESSIONS_OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secrets.oidcCredentials }}/SESSIONS_OIDC_CLIENT_SECRET
    - secretKey: SESSIONS_OIDC_AUDIENCE
      remoteRef:
        key: {{ .Values.secrets.oidcCredentials }}/SESSIONS_OIDC_AUDIENCE
