when:
    event: push

variables:
    - &buildx-plugin "woodpeckerci/plugin-docker-buildx:6.0.2"
    - &repo "registry.mareshq.com/mareshq-websites/mares-cz"
    - &platforms "linux/amd64"

steps:
    build-container:
        image: *buildx-plugin
        settings:
            repo: *repo
            platforms: *platforms
            tag: commit-${CI_COMMIT_SHA:0:16}
            logins:
                - registry: https://registry.mareshq.com
                  username:
                      from_secret: registry_username
                  password:
                      from_secret: registry_password
