when:
  - event: push

depends_on:
  - test

variables:
  - &node_image "node:22"
  - &vercel_org_id "team_f23XWAi9OmTD7W6Ej4kmydWK"
  - &vercel_project_id "prj_hlccJk033PGAZp1HIxgW2Qq8s8om"
  - &strapi_api_url "https://cms.mareshq.com/api"
  - &notion_training_sessions_database_id "1eb611d502b1807bbc5df523a3acc322"

workspace:
  base: /woodpecker
  path: src/mareshq-websites/mares.cz-deploy

steps:
  - name: setup
    image: *node_image
    commands:
      - export PNPM_STORE_DIR=${{CI_WORKSPACE}}/.pnpm-store
      - corepack enable
      - corepack prepare pnpm@latest-10 --activate
      - pnpm config set store-dir $PNPM_STORE_DIR
      - SHELL="$(which bash)" pnpm setup
      - source ~/.bashrc
      - pnpm add -g vercel

  - name: deploy:production
    image: *node_image
    commands:
      - vercel pull --yes --environment=production --token=$${VERCEL_TOKEN}
      - vercel build --prod --token=$${VERCEL_TOKEN}
      - vercel deploy --prod --prebuilt --token=$${VERCEL_TOKEN}
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_token
      STRAPI_API_TOKEN:
        from_secret: strapi_api_token
      NOTION_API_KEY:
        from_secret: notion_api_key
      VERCEL_ORG_ID: *vercel_org_id
      VERCEL_PROJECT_ID: *vercel_project_id
      STRAPI_API_URL: *strapi_api_url
      NOTION_TRAINING_SESSIONS_DATABASE_ID: *notion_training_sessions_database_id
    when:
      - branch: main

  - name: deploy:preview
    image: *node_image
    commands:
      - vercel pull --yes --environment=preview --token=$${VERCEL_TOKEN}
      - vercel build --token=$${VERCEL_TOKEN}
      - DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=$${VERCEL_TOKEN})
      - vercel alias $DEPLOY_URL website-$${CI_COMMIT_REF_SLUG}.vercel.app --token=$${VERCEL_TOKEN}
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_token
      STRAPI_API_TOKEN:
        from_secret: strapi_api_token
      NOTION_API_KEY:
        from_secret: notion_api_key
      VERCEL_ORG_ID: *vercel_org_id
      VERCEL_PROJECT_ID: *vercel_project_id
      STRAPI_API_URL: *strapi_api_url
      NOTION_TRAINING_SESSIONS_DATABASE_ID: *notion_training_sessions_database_id
    when:
      - branch:
          exclude: [main]
