name: build, test, deploy

on:
  push:
  pull_request:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  build-test:
    name: build and test app
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: lint check
        shell: bash
        run: pnpm lint

      - name: format check
        shell: bash
        run: pnpm format

      - name: test
        shell: bash
        run: pnpm test

  deploy-preview:
    if: "github.ref != 'refs/heads/main' || github.ref != 'refs/heads/production'"
    needs: [build-test]
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preview
      environment-url: https://preview.mares.cz

  deploy-staging:
    if: "github.ref == 'refs/heads/main'"
    needs: [build-test]
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      environment-url: https://beta.mares.cz
